import { NextPage } from "next";
import Head from "next/head";
import { AboutContent } from "../components/about-content";
import { Layout } from "../components/layout";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About | Ondřej Pešička</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <AboutContent />
      </Layout>
    </>
  );
};

export default About;
